name: "Build and Distribute Docker to DockerHub"
on: [push]

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Read VERSION
        id: read_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION
      - name: "Build Python Base Docker image"
        uses: "docker/build-push-action@v1"
        with:
          repository: "ubitecag/jenkins-docker-python"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          target: "ubitec_jenkins_python_base"
          tags: base-${{ steps.read_version.outputs.content }}